name: adaptive_sizer
description: This package will help you to resize app based on scale ratio of design and device.
version: 0.0.4
homepage: https://github.com/BobanBaby

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

 